### YamlMime:ManagedReference
items:
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  id: FirstChanceExceptionEventArgs
  children:
  - System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)
  - System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception
  langs:
  - csharp
  name: FirstChanceExceptionEventArgs
  nameWithType: FirstChanceExceptionEventArgs
  fullName: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  type: Class
  summary: "Inneholder data for varslingshendelsen oppstår når forvaltet først det oppstår et unntak, før common language runtime søkes etter hendelsesbehandling."
  remarks: "Denne klassen gir et unntak behandlingsprogram for den <xref:System.AppDomain.FirstChanceException?displayProperty=fullName>hendelsen tilgang til unntaket.</xref:System.AppDomain.FirstChanceException?displayProperty=fullName>"
  example:
  - "The following example creates a series of application domains named `Child_0` through `Child_3`, with a `Worker` object in each application domain. Each `Worker` object has a reference to the `Worker` object in the next application domain, except for the `Worker` in the last application domain. The <xref:System.AppDomain.FirstChanceException> event is handled in all application domains except `Child_1`.  \n  \n When the application domains have been created, the default application domain calls the `TestException` method for the first child application domain. Each `Worker` object calls the `TestException` method for the next, until the last `Worker` throws an exception that is either handled or unhandled. Thus, the current thread passes through all the application domains, and `TestException` is added to the stack in each application domain.  \n  \n When the last `Worker` object handles the exception, the <xref:System.AppDomain.FirstChanceException> event is raised only in the last application domain. The other application domains never get a chance to handle the exception, so the event is not raised.  \n  \n When the last `Worker` object does not handle the exception, the <xref:System.AppDomain.FirstChanceException> event is raised in each application domain that has an event handler. After each event handler has finished, the stack continues to unwind until the exception is caught by the default application domain.  \n  \n> [!NOTE]\n>  To see how the stack display grows as the event is raised closer and closer to the default application domain, change `e.Exception.Message` to `e.Exception` in the `FirstChanceHandler` event handlers. Notice that when `TestException` is called across application domain boundaries, it appears twice: once for the proxy and once for the stub.  \n  \n [!code-vb[System.AppDomain.FirstChanceException#1](~/add/codesnippet/visualbasic/t-system.runtime.excepti_1.vb)]\n [!code-cs[System.AppDomain.FirstChanceException#1](~/add/codesnippet/csharp/t-system.runtime.excepti_1.cs)]"
  syntax:
    content: 'public class FirstChanceExceptionEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)
  id: '#ctor(System.Exception)'
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  langs:
  - csharp
  name: FirstChanceExceptionEventArgs(Exception)
  nameWithType: FirstChanceExceptionEventArgs.FirstChanceExceptionEventArgs(Exception)
  fullName: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.FirstChanceExceptionEventArgs(Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.ExceptionServices
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs&quot;> </xref> klassen med en angitt unntak."
  remarks: "Denne konstruktøren kalles av common language runtime ikke av en kode for programmet."
  syntax:
    content: public FirstChanceExceptionEventArgs (Exception exception);
    parameters:
    - id: exception
      type: System.Exception
      description: "Unntak som oppstod bare av behandlet kode, og som skal undersøkes av den <xref href=&quot;System.AppDomain.UnhandledException&quot;> </xref> hendelsen."
  overload: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception
  id: Exception
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  langs:
  - csharp
  name: Exception
  nameWithType: FirstChanceExceptionEventArgs.Exception
  fullName: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Runtime.ExceptionServices
  summary: "Forvaltet unntak-objektet som samsvarer med unntak i behandlet kode."
  remarks: "Metoden som behandler den <xref:System.AppDomain.UnhandledException?displayProperty=fullName>hendelsen kan se unntaket og utføre nødvendige logging eller andre notification-tjenester.</xref:System.AppDomain.UnhandledException?displayProperty=fullName>       For eksempelkode, kan du se <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>"
  syntax:
    content: public Exception Exception { get; }
    return:
      type: System.Exception
      description: "Nylig thrown unntaket."
  overload: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  isExternal: false
  name: FirstChanceExceptionEventArgs(Exception)
  nameWithType: FirstChanceExceptionEventArgs.FirstChanceExceptionEventArgs(Exception)
  fullName: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.FirstChanceExceptionEventArgs(Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  isExternal: false
  name: Exception
  nameWithType: FirstChanceExceptionEventArgs.Exception
  fullName: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor*
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  isExternal: false
  name: FirstChanceExceptionEventArgs
  nameWithType: FirstChanceExceptionEventArgs.FirstChanceExceptionEventArgs
- uid: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception*
  parent: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
  isExternal: false
  name: Exception
  nameWithType: FirstChanceExceptionEventArgs.Exception
