### YamlMime:ManagedReference
items:
- uid: System.Runtime.Remoting.ServerException
  id: ServerException
  children:
  - System.Runtime.Remoting.ServerException.#ctor
  - System.Runtime.Remoting.ServerException.#ctor(System.String)
  - System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ServerException
  nameWithType: ServerException
  fullName: System.Runtime.Remoting.ServerException
  type: Class
  summary: "Unntak som er registrert til å kommunisere feil til klienten når klienten kobler til ikke .NET Framework-programmer som ikke kan slette unntak."
  remarks: "ServerException bruker HRESULT COR_E_SERVER, som har verdien 0x8013150E.       ServerException bruker standard <xref:System.Object.Equals%2A>implementering, som støtter referanse likhet.</xref:System.Object.Equals%2A>       Hvis du vil se en liste med opprinnelige verdier for en forekomst av ServerException, kan du se ServerException konstruktører."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class ServerException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.Remoting.ServerException.#ctor
  id: '#ctor'
  parent: System.Runtime.Remoting.ServerException
  langs:
  - csharp
  name: ServerException()
  nameWithType: ServerException.ServerException()
  fullName: System.Runtime.Remoting.ServerException.ServerException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Runtime.Remoting.ServerException&quot;> </xref> klasse standardegenskapene."
  remarks: "<xref:System.Runtime.Remoting.ServerException>arver fra <xref:System.SystemException>klasse.</xref:System.SystemException></xref:System.Runtime.Remoting.ServerException> Tabellen nedenfor viser første egenskapsverdier for en forekomst av klassen <xref:System.Runtime.Remoting.ServerException>: | Egenskapen | Verdien |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| En tom streng (&quot;&quot;) |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.ServerException>"
  syntax:
    content: public ServerException ();
    parameters: []
  overload: System.Runtime.Remoting.ServerException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.ServerException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.Remoting.ServerException
  langs:
  - csharp
  name: ServerException(String)
  nameWithType: ServerException.ServerException(String)
  fullName: System.Runtime.Remoting.ServerException.ServerException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Runtime.Remoting.ServerException&quot;> </xref> klassen med en angitt melding."
  remarks: "<xref:System.Runtime.Remoting.ServerException>arver fra <xref:System.SystemException>klasse.</xref:System.SystemException></xref:System.Runtime.Remoting.ServerException> Tabellen nedenfor viser første egenskapsverdier for en forekomst av klassen <xref:System.Runtime.Remoting.ServerException>: | Egenskapstype | Betingelse |   |-------------------|---------------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| Den `message` streng |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.ServerException>"
  syntax:
    content: public ServerException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Meldingen som beskriver unntaket"
  overload: System.Runtime.Remoting.ServerException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.Remoting.ServerException
  langs:
  - csharp
  name: ServerException(String,Exception)
  nameWithType: ServerException.ServerException(String,Exception)
  fullName: System.Runtime.Remoting.ServerException.ServerException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "Initialiserer en ny forekomst av den <xref href=&quot;System.Runtime.Remoting.ServerException&quot;> </xref> klassen med en angitt feilmelding og en referanse til det interne unntaket er årsaken til dette unntaket."
  remarks: "Et unntak som er registrert som en direkte resultatet av et tidligere unntak må inkludere en referanse til det tidligere unntaket i den <xref:System.Exception.InnerException%2A>egenskapen.</xref:System.Exception.InnerException%2A> Den <xref:System.Exception.InnerException%2A>egenskapen returnerer den samme verdien som er sendt til konstruktøren, eller `null` hvis den <xref:System.Exception.InnerException%2A>egenskapen leverer ikke internt unntak verdien til konstruktøren.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Tabellen nedenfor viser første egenskapsverdier for en forekomst av klassen <xref:System.Runtime.Remoting.ServerException>: | Egenskapen | Verdien |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Internt unntak-referanse |   | <xref:System.Exception.Message%2A>| Feil melding strengen |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.ServerException>"
  syntax:
    content: public ServerException (string message, Exception InnerException);
    parameters:
    - id: message
      type: System.String
      description: "Feilmelding som forklarer hvorfor unntaket."
    - id: InnerException
      type: System.Exception
      description: "Unntaket er årsaken til den gjeldende unntaket. Hvis den `InnerException` -parameteren er ikke <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, oppstår det gjeldende unntaket i en <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokken som behandler det interne unntaket."
  overload: System.Runtime.Remoting.ServerException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.Runtime.Remoting.ServerException.#ctor
  parent: System.Runtime.Remoting.ServerException
  isExternal: false
  name: ServerException()
  nameWithType: ServerException.ServerException()
  fullName: System.Runtime.Remoting.ServerException.ServerException()
- uid: System.Runtime.Remoting.ServerException.#ctor(System.String)
  parent: System.Runtime.Remoting.ServerException
  isExternal: false
  name: ServerException(String)
  nameWithType: ServerException.ServerException(String)
  fullName: System.Runtime.Remoting.ServerException.ServerException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Remoting.ServerException.#ctor(System.String,System.Exception)
  parent: System.Runtime.Remoting.ServerException
  isExternal: false
  name: ServerException(String,Exception)
  nameWithType: ServerException.ServerException(String,Exception)
  fullName: System.Runtime.Remoting.ServerException.ServerException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.Remoting.ServerException.#ctor*
  parent: System.Runtime.Remoting.ServerException
  isExternal: false
  name: ServerException
  nameWithType: ServerException.ServerException
